production:
  daily_inbox_summary:
    class: InboxSummaryJob
    queue: default
    schedule: at 9am every day

development:
  daily_inbox_summary:
    class: InboxSummaryJob
    queue: default
    schedule: at 9am every day
